name: Expo Build APK

on:
  push:
    branches:
      - secondary  # Triggers only when you push to the 'secondary' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Login to Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: npx expo login --token $EXPO_TOKEN

      - name: Build APK
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: npx expo build:android --type apk --non-interactive
